version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass

  app:
    build: . 
    command: npm start
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
